version: '3.4'

services:
  sensor_device_service:
    image: ${DOCKER_REGISTRY-}sensordeviceservice
    build:
      context: .
      dockerfile: IOT_Traffic_Tracker_Microservices/Dockerfile

  data_service:
    image: ${DOCKER_REGISTRY-}dataservice
    build:
      context: .
      dockerfile: Data_Service/Dockerfile

